apiVersion: v1
kind: Service
metadata:
  name: onlyoffice-document-server
  namespace: nextcloud
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  - name: https
    port: 443
    targetPort: 443
    protocol: TCP
  selector:
    app: onlyoffice-document-server
